server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-movie
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3307/movie-dev
  username: usr-movie
  password: pwd-movie

info:
  application:
    name: api-movie
eureka:
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#Si quiere que ejecute con H2 y no con SQL descomente lo sigueinte, y comente el datasource anterior
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#    jpa:
#      open-in-view: false
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.H2Dialect
#          format_sql: true
#    h2:
#      console:
#        enabled: true
#       path: /h2-console
# logging:
#    level:
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

